udo: false

language: cpp

os:
  - linux
  - osx

env:
  # code analysis
  - TASK=lint
  # build mxnet.so with CUDA
  - TASK=build
  # run tests/cpp
  - TASK=cpp_test

# dependent apt packages
addons:
  apt:
    packages:
      - doxygen
      - wget
      - git
      - libcurl4-openssl-dev
      - unzip
      - libatlas-dev
      - libopencv-dev
      - gcc-4.8
      - g++-4.8

before_install:
  - export NVCC_PREFIX=${HOME}
#  - source dmlc-core/scripts/travis/travis_setup_env.sh

install:
  - source tests/travis/setup.sh

script:
  - tests/travis/run_test.sh

cache:
  directories:
    - ${HOME}/.cache/usr

#before_cache:
#  - dmlc-core/scripts/travis/travis_before_cache.sh

notifications:
# Emails are sent to the committer's git-configured email address by default,
  email:
    on_success: change
    on_failure: always
  #slack: dmlc:NmroCzntCiWOuxUZpii40USd
